"""make embedding_model nullable, add is_embedded flag

Revision ID: b74059d1af4c
Revises: 41cf7b7f5659
Create Date: 2026-09-12 04:26:46.843249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b74059d1af4c'
down_revision: Union[str, None] = '41cf7b7f5659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('is_embedded', sa.Boolean(), nullable=False))
    op.alter_column('document_chunks', 'embedding_model',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding_model',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('document_chunks', 'is_embedded')
    # ### end Alembic commands ###
